# Environment

export CHROME_BIN="chromium-browser"
export EDITOR=nvim # Use neovim as the default editor.
export VISUAL=nvim
export MANPAGER='nvim +Man!' # Use neovim as manpager
export ANDROID_HOME="$HOME/Android/Sdk"
export ANDROID_SDK_ROOT="$HOME/Android/Sdk"

test -f ~/.1password/agent.sock && export SSH_AUTH_SOCK=~/.1password/agent.sock


# Aliases

alias nvimc="cd ~/.config/nvim && nvim"

