min_version = "2026.8.11"  # Need auto_update setting

[settings]
dotfiles.root = "~/.dotfiles"
dotfiles.default_mode = "symlink"

[dotfiles]
"~/.config/fish/**/*.fish" = ".config/fish/**/*.fish"
"~/.config/ghostty" = { mode = "symlink-each", source = ".config/ghostty" }
"~/.config/git" = ".config/git"
"~/.config/jj" = { mode = "symlink-each", source = ".config/jj" }
"~/.config/kitty" = { mode = "symlink-each", source = ".config/kitty" }
"~/bin" = { mode = "symlink-each", source = "bin" }
"~/.config/mise" = { mode = "symlink-each", source = ".config/mise" }
"~/.config/nvim" = ".config/nvim"
"~/.config/starship.toml" = ".config/starship.toml"
"~/dev/.gitconfig" = "dev/.gitconfig"
"~/dev/uni/.gitconfig" = "dev/uni/.gitconfig"
"~/.bashrc/shell-config" = { block = """
source ~/.dotfiles/.shell-common.sh
source ~/.dotfiles/.bash-config.sh
  """ }

[tasks.bootstrap]
depends_post = ["install-fonts"]
