#!/usr/bin/env bash

echo "Installing from Brewfile"
cd ~
brew bundle
cd -
echo "Installed from Brewfile"

mise_packages=(
	"bun"
	"cargo-binstall"
	"go"
	"node@lts"
	"rust"
	"starship"
	"uv"
)

mise_install_packages=$(printf "%s\n" "${mise_packages[@]}" | fzf --header "Select packages to install using mise" --multi --preview-window right --preview "mise tool {}")

if [ -n "$mise_install_packages" ]; then
	install_command=$(echo "$mise_install_packages" | tr '\n' ' ')

	echo "Installing: $install_command"
	mise use -g $install_command

else
	echo "No package selected."
fi

mise settings set npm.package_manager bun

if [[ ! -f ~/.config/starship.toml ]]; then
	starship preset nerd-font-symbols -o ~/.config/starship.toml
	echo "Setup starship preset"
fi

echo "source ~/.shell_common.conf" >>~/.bashrc
echo "source ~/.bash_config.sh" >>~/.bashrc

echo "source ~/.shell_common.conf" >>~/.config/fish/config.fish
echo "source ~/.fish_config.fish" >>~/.config/fish/config.fish
